SELECT * FROM FACEBOOK;

SELECT COUNT(*)
FROM FACEBOOK
WHERE AGE>15;


SELECT COUNT(*) 
FROM FACEBOOK
WHERE GENDER='male';

SELECT COUNT(*)
FROM FACEBOOK
WHERE GENDER='female' and AGE>18;

SELECT COUNT(*)
FROM FACEBOOK
WHERE DOB_YEAR=1999;

SELECT COUNT(*),DOB_YEAR
FROM FACEBOOK
GROUP BY DOB_YEAR;

SELECT COUNT(*)
FROM FACEBOOK
WHERE GENDER='male' and AGE>15;

SELECT COUNT(*),AGE
FROM FACEBOOK
GROUP BY AGE;

SELECT ROUND(100.0*SUM(CASE WHEN GENDER='female' THEN 1 ELSE 0 END)/COUNT(*),2) FEMALE_PERC
FROM FACEBOOK
WHERE AGE>17;

SELECT ROUND(100.0*SUM(CASE WHEN GENDER='female' THEN 1 ELSE 0 END)/COUNT(*),2) FEMALE_PERC
FROM FACEBOOK;

SELECT COUNT(*),AGE
FROM FACEBOOK
GROUP BY AGE;