SELECT * FROM FACEBOOK;

SELECT COUNT(*)
FROM FACEBOOK;

SELECT ROUND(100.0*SUM(CASE WHEN GENDER='male' THEN 1 ELSE 0 END)/COUNT(*),2) MALE_PERC
FROM FACEBOOK;

SELECT ROUND(100.0*SUM(CASE WHEN GENDER='female' THEN 1 ELSE 0 END)/COUNT(*),2) FEMALE_PERC
FROM FACEBOOK;

SELECT ROUND(100.0*SUM(CASE WHEN GENDER='male' THEN 1 ELSE 0 END)/COUNT(*),2) MALE_PERC
FROM FACEBOOK
WHERE AGE>15;

SELECT ROUND(100.0*SUM(CASE WHEN GENDER='female' THEN 1 ELSE 0 END)/COUNT(*),2) FEMALE_PERC
FROM FACEBOOK
WHERE AGE>15;