SELECT * FROM FACEBOOK;

SELECT COUNT(*)
FROM FACEBOOK 
WHERE GENDER='female' and DOB_YEAR=1999;

SELECT COUNT(*)
FROM FACEBOOK
WHERE GENDER='female' and (DOB_YEAR BETWEEN 1997 AND 2000);

SELECT *
FROM FACEBOOK
where AGE>15;

SELECT * FROM FACEBOOK WHERE GENDER='male';


SELECT * 
FROM FACEBOOK
WHERE USERID=21004073;

