--1 Question
SELECT * FROM FACEBOOK;

--2 Question
SELECT ROUND(100.0*SUM(CASE WHEN GENDER='male' THEN 1 ELSE 0 END)/COUNT(*),2) MALE_PERC
FROM FACEBOOK;

--3 Question
SELECT ROUND(100.0*SUM(CASE WHEN GENDER='female' THEN 1 ELSE 0 END)/COUNT(*),2) FEMALE_PERC
FROM FACEBOOK;

--4 Question
SELECT ROUND(100.0*SUM(CASE WHEN GENDER='male' AND AGE>15 THEN 1 ELSE 0 END)/COUNT(*),2) MALE_PERC
FROM FACEBOOK;

--5 Question
SELECT ROUND(100.0*SUM(CASE WHEN GENDER='female' AND AGE>15 THEN 1 ELSE 0 END)/COUNT(*),2) FEMALE_PERC
FROM FACEBOOK; 