-- 1 QUESTION
SELECT * FROM FACEBOOK
WHERE AGE>15;


-- 2 QUESTION 
SELECT * FROM FACEBOOK
WHERE GENDER='male' and age>15;

-- 3 QUESTION
SELECT * FROM FACEBOOK
WHERE GENDER='female';

-- 4 QUESTION
SELECT * FROM FACEBOOK
WHERE DOB_YEAR=1999;

-- 5 QUESTION
SELECT COUNT(*),DOB_YEAR FROM FACEBOOK
GROUP BY DOB_YEAR
ORDER BY DOB_YEAR;

-- 6 Question
SELECT COUNT(*) FROM FACEBOOK
WHERE GENDER='male' AND AGE>15;


--7 Question
SELECT COUNT(*),AGE FROM FACEBOOK
GROUP BY AGE
ORDER BY AGE;

--8 Question
SELECT ROUND(100.0*SUM(CASE WHEN GENDER='female' THEN 1 ELSE 0 END)/COUNT(*),2) FEMALE_PERCENTAGE FROM FACEBOOK
WHERE AGE>17;

-- 9 Question
SELECT ROUND(100.0*SUM(CASE WHEN GENDER='female' THEN 1 ELSE 0 END)/COUNT(*),2) FEMALE_PERCENTAGE 
FROM FACEBOOK;

--10 Question
SELECT COUNT(*),AGE FROM FACEBOOK
GROUP BY AGE
ORDER BY AGE;

