--1 Question
SELECT COUNT(*) COUNT_MALE FROM FACEBOOK
WHERE GENDER='male' AND DOB_YEAR=1999;

--2 Question
SELECT COUNT(*) COUNT_FEMALE FROM FACEBOOK
WHERE GENDER='female' AND DOB_YEAR BETWEEN 1997 AND 2000;

--3 Question
SELECT * FROM FACEBOOK
WHERE AGE>15;

--4 Question
SELECT * FROM FACEBOOK
WHERE GENDER='male';

--5 Question
SELECT * FROM FACEBOOK
WHERE USERID=2104073;

